name: PHP

on:
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 15
      matrix:
        laravel-version: ['12.0', ^10.0, ^11.0]
        php-versions: ['8.1', '8.2', '8.3']
        exclude:
          - laravel-version: ^10.0
            php-versions: '8.1'
          - laravel-version: ^11.0
            php-versions: '8.1'
          - laravel-version: '12.0'
            php-versions: '8.1'

    name: PHP ${{ matrix.php-versions }} on ${{ matrix.laravel-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xdebug
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require --no-update --no-interaction "illuminate/support:${{ matrix.laravel-version }}" php-coveralls/php-coveralls
          composer update --no-interaction --prefer-dist --no-suggest

      - name: Lint composer.json
        run: composer validate

      - name: Run Tests
        run: composer test:ci

      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash)
